### ISSUE TITLE
Spotify Integration?

### ISSUE THREAD

**Issue by hrjs84** [ptrk95/MMM-MusicOnDemand#1]
This is exactly the type of module I have been looking for, one which will integrate with the voice assistant to search and control a music stream! However, I think it'd be great to be able to use Spotify instead of Deezer, is there a way this could be supported?

**Comment by ptrk95** [comment]
Unfortunately Spotify seem to have discontinued the support for the webplayer on chromium. (raspberry pi)
Since this module only works with chromium/chrome it won't work until spotify continue its support on it. 
I tried the solution [here](https://www.raspberrypi.org/forums/viewtopic.php?t=176529) but it's not working for me and the last two comments say the same. 

If you get the spotify webplayer working on chromium (raspberry pi) you can write again how you did it and then I can try to do the same module for spotify.
